# Site settings
author: Theo Johnson
title: T2wise4u
header-img: img/home-bg.png
email: theoonetj@gmail.com
copyright_name: Theo Johnson
description: > # this means to ignore newlines until "baseurl:"
  Road to Software Development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Theoonetj

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
